### PR TITLE
Only send ORCID emails when article is accepted

### PR DESCRIPTION
**Pull request by ajnyga**
Fix for master branch, see https://github.com/pkp/pkp-lib/issues/4998#issuecomment-565360412

### CODE REVIEW

**Comment by ajnyga** [comment]
I think leaving the old setting name would be a source of confusion. 

I can add a cleanup script to the 3.2 upgrade.

(There is actually a whole bunch of old OJS2 settings that are not used anymore and are still existing in the db. Like `useLayoutEditors, useProofreaders, subscriptionFax, boardEnabled, requireAuthorCompetingInterests, contactFax, authorSelectsEditor, allowRegReader, allowRegAuthor, allowRegReviewer, enableComments, journalTitleAltLanguages, profileAltLanguages, articleAltLanguages, copySubmissionAckSpecified, homeHeaderTitleType, homeHeaderTitleTypeAlt1, homeHeaderTitleAlt1, homeHeaderTitleTypeAlt2, homeHeaderTitleAlt2, pageHeaderTitleType, pageHeaderTitleTypeAlt1, pageHeaderTitleAlt1, pageHeaderTitleTypeAlt2, pageHeaderTitleAlt2, reviewerDatabaseLinks, metaSubjectClassUrl, copyeditInstructions, provideRefLinkInstructions, proofInstructions, notifyAllAuthorsOnDecision`)

**Comment by ajnyga** [comment]
@ctgraham https://github.com/pkp/ojs/pull/2560

**Comment by ajnyga** [comment]
@ctgraham I know I said the old variable name would be a source of confusion, but I think we really need these changes to the plugin ASAP so I will change my pr so that the variable name does not change and start a new issue here that will aim to change that name later on. I mean only people working with the code will see it...

**Comment by asmecher** [comment]
@ajnyga, is this ready for merge? I'd need to resolve the merge conflict, but would be happy to tackle that with your blessing.

**Comment by ajnyga** [comment]
yes, it is ready

**Comment by asmecher** [comment]
Merged manually -- thanks to you both!

**Pull request closed without merging**
