### PR TITLE
Moved all the content into the <form> tag to avoid displaying duplicated content

### PR DESCRIPTION
**Pull request by jonasraoni**
Moved all the content into the <form> tag to avoid displaying duplicated content in case there's a submit error (pkp/pkp-lib#4533)

### CODE REVIEW

**Comment by jonasraoni** [comment]
@asmecher

**Comment by asmecher** [comment]
Does this maybe include some inadvertent changes? Looking e.g. at https://github.com/pkp/orcidProfile/pull/67/files#diff-252573571076a23b160f105163d441f1R34.

**Comment by jonasraoni** [comment]
Hmm, it should be ok, I've just moved the `<div>` inside the `<form>` and indended :)
The line that you've marked should be matched against this one: https://github.com/pkp/orcidProfile/pull/67/files#diff-252573571076a23b160f105163d441f1L33

**Comment by asmecher** [comment]
@jonasraoni, ah, I see it -- the `diff` syntax highlighting misrepresented what was being change. You're right, it's just indentation and a few elements moved. Merged, thanks!

**Pull request merged**
