### PR TITLE
pkp/pkp-lib#9296 Sandbox settings

### PR DESCRIPTION
**Pull request by touhidurabir**
for pkp/pkp-lib#9296

### CODE REVIEW

**Comment by asmecher** [comment]
@ewhanson, would you prefer that this was merged here, or that the functionality was separately ported into your work for `main`?

**Comment by ewhanson** [comment]
Hey @asmecher, probably easier for me to add directly as I've already removed pretty much all of the plugin code already. If you don't mind, I'll keep this PR open until I get it added then close it.

**Comment by asmecher** [comment]
That sounds fine to me, thanks. Would you like me to keep the issue it's attached to open, or will this be enough of a reminder?

**Comment by ewhanson** [comment]
Added to WIP ORCID changes on main. Closing as complete.

**Pull request closed without merging**
