### PR TITLE
Support for OPS and fixes for OJS master

### PR DESCRIPTION
**Pull request by ajnyga**

### CODE REVIEW

**Comment by asmecher** [comment]
Looks good, thanks, @ajnyga! I'll look into creating some automated tests for this that'll run against all 3 apps.

**Comment by ajnyga** [comment]
I do not think this has been tested with OMP yet though...

**Comment by asmecher** [comment]
You're right, I suspect not, though it would be a logical thing (and probably fairly quick) to adapt. I'll see what it looks like.

**Comment by ajnyga** [comment]
yeah should be only a couple of things needed.

Note that I did not test the member API functions there yet, so they probably have references to submission etc.

**Pull request merged**
